Feature/personal tasks
arpesh28/ekagratha-api pull request #13
Opened 2024-02-10 04:03 UTC by omkarvaigankar8

Personal Tasks CRUD created

2024-02-10 05:06 UTC, arpesh28 requested changes

2024-02-10 05:06 UTC, arpesh28 commented on src/config/zodSchema.config.ts
create a new folder "types" and add types.ts, interface.ts & enums.ts. And export the enums from enum.ts

2024-02-10 05:06 UTC, arpesh28 commented on src/config/constants.config.ts
You don't need the constants if you're using enums

2024-02-10 05:07 UTC, arpesh28 commented
> Personal Tasks CRUD created

Please mention and tag the issue number in here.

2024-02-12 06:26 UTC, omkarvaigankar8 commented on src/config/zodSchema.config.ts
added required types

2024-02-12 06:26 UTC, omkarvaigankar8 commented on src/config/constants.config.ts
removed the constant

2024-02-12 06:28 UTC, arpesh28 approved these changes

2024-02-12 08:09 UTC, arpesh28 approved these changes
LGTM!

2024-02-12 08:09 UTC, merged